dhan_client_id = "1100912843"
dhan_access_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJkaGFuIiwicGFydG5lcklkIjoiIiwiZXhwIjoxNzE0MjEzMzAxLCJ0b2tlbkNvbnN1bWVyVHlwZSI6IlNFTEYiLCJ3ZWJob29rVXJsIjoiIiwiZGhhbkNsaWVudElkIjoiMTEwMDkxMjg0MyJ9.NCBXmMX0d5Nx-f-dOyR0rL3K_tz5gQJsrLegaq-xCEt3D5b_Bq2G2YoWRmT6rOJzbjcjyeDVzlLi-fnujoQ7rA"
exchange = 'NSE'
temp_stock_to_track = { 
                        "KOTAKBANK": {"daily": [1780.9]}, 
                        "UPL": {"weekly":[518.4, 508.8]}, 
                        "INDUSINDBK": {"weekly":[1353, 1336.95], 
                                       "daily": [1396.55]},
                        "M_M":{"weekly":[2575, 2506, 2900, 2887.80]},
                        "LT": {"daily":[3801]}, 
                        "INFY":{"daily":[1844]},
                        "BHARTIARTL": {"daily":[]},
                        "TECHM": {"weekly":[]},
                        "HCLTECH": {"weekly":[1472],
                                    "daily":[1602, 1598]},
                        "RELIANCE": {"weekly":[3074, 3110],
                                     "daily": [3011.5]},
                        "SBIN": {"daily": [897,905]},
                        "SUNPHARMA": {"weekly": []},
                        "JSWSTEEL": {"weekly": [909, 915], 
                                     "daily": []},
                        "TITAN": {"weekly": [2802, 3361.05, 3382], 
                                  "monthly":[2814.7, 2679.3]},
                        "HEROMOTOCO": {"weekly": [5280, 5119]},
                        "HINDALCO": {"daily":[656,683, 690]},
                        "HEROMOTOCO": {"weekly": [5280, 5225, 5119]},
                        "ITC": {"daily": [479.45],
                                "weekly": [465.85, 463.25]},
                        "NESTLEIND": {"daily": [2438, 2425.6]},
                        "BRITANNIA": {"weekly": [5787.05]},
                        "CIPLA":{"daily": [1501.6]},
                        "ADANIPORTS":{"weekly": [1510.60]},
                        "SBILIFE": {"daily": [1645, 1632.95]},
                        "HDFCLIFE": {"daily": [682.05, 675]}
                        }

nifty_50_stocks = ["HDFCBANK",
"RELIANCE",
"INFY",
"ICICIBANK",
"TCS",
"KOTAKBANK",
"HINDUNILVR",
"BHARTIARTL",
"AXISBANK",
"LT",
"WIPRO",
"SBIN",
"MARUTI",
"NTPC",
"ONGC",
"TECHM",
"IOC",
"HCLTECH",
"BAJAJFINSV",
"ASIANPAINT",
"SUNPHARMA",
"JSWSTEEL",
"DMART",
"TITAN",
"INDUSINDBK",
"ULTRACEMCO",
"SHREECEM",
"BAJFINANCE",
"DIVISLAB",
"UPL",
"COALINDIA",
"HEROMOTOCO",
"HINDALCO",
"GRASIM",
"M_M",
"BAJAJ_AUTO",
"ITC",
"POWERGRID",
"NESTLEIND",
"DRREDDY",
"BRITANNIA",
"GAIL",
"IOC",
"CIPLA",
"ADANIPORTS",
"HINDPETRO",
"SBILIFE",
"EICHERMOT",
"HDFCLIFE"]

small_cap_stocks = ["AARTIIND",
"AAVAS",
"AFFLE",
"ALOKINDS",
"ARE_M",
"AMBER",
"ANGELONE",
"APARINDS",
"BLS",
"BSOFT",
"BLUESTARCO",
"CESC",
"CIEINDIA",
"CANFINHOME",
"CASTROLIND",
"CEATLTD",
"CENTRALBK",
"CDSL",
"CENTURYTEX",
"CHAMBLFERT",
"CUB",
"COCHINSHIP",
"CAMS",
"CREDITACC",
"CROMPTON",
"CYIENT",
"DATAPATTNS",
"EQUITASBNK",
"EXIDEIND",
"FINCABLES",
"FSL",
"FIVESTAR",
"GLENMARK",
"MEDANTA",
"GRAPHITE",
"GESHIP",
"GMDCLTD",
"GNFC",
"GSPL",
"HFCL",
"HAPPSTMNDS",
"HSCL",
"HINDCOPPER",
"HONASA",
"HUDCO",
"IDFC",
"IIFL",
"IRB",
"IRCON",
"ITI",
"INDIAMART",
"IEX",
"IOB",
"INTELLECT",
"JBCHEPHARM",
"JBMA",
"J_KBANK",
"JYOTHYLAB",
"KARURVYSYA",
"KEC",
"MGL",
"MANAPPURAM",
"MRPL",
"MCX",
"NATCOPHARM",
"NBCC",
"NCC",
"NLCINDIA",
"NSLNISP",
"NH",
"NATIONALUM",
"NAVINFLUOR",
"NAM_INDIA",
"OLECTRA",
"PNBHOUSING",
"PVRINOX",
"PPLPHARMA",
"PRAJIND",
"RRKABEL",
"RBLBANK",
"RITES",
"RADICO",
"RKFORGE",
"RAYMOND",
"REDINGTON",
"RENUKA",
"SHYAMMETL",
"SONATSOFTW",
"SWANENERGY",
"TANLA",
"TATAINVEST",
"TTML",
"TEJASNET",
"TITAGARH",
"TRIDENT",
"TRITURBINE",
"UCOBANK",
"UJJIVANSFB",
"WELSPUNLIV",
"ZENSARTECH"]



mid_cap_stocks = ["ACC",
"APOLLOTYRE",
"ASHOKLEY",
"SKFINDIA",
"ATUL",
"BALKRISIND",
"BATAINDIA",
"BAYERCROP",
"BHARATFORG",
"ABBOTINDIA",
"CARBORUNIV",
"COROMANDEL",
"CGPOWER",
"DEEPAKNTR",
"ESCORTS",
"GLAXO",
"KANSAINER",
"GRINDWELL",
"INDHOTEL",
"LINDEINDIA",
"CUMMINSIND",
"RAMCOCEM",
"MFSL",
"MRF",
"PEL",
"SCHAEFFLER",
"PGHH",
"SUNDRMFAST",
"SUNDARMFIN",
"SUPREMEIND",
"TATACHEM",
"VOLTAS",
"PATANJALI",
"KAJARIACER",
"HONAUT",
"GODREJIND",
"3MINDIA",
"TIMKEN",
"TATACOMM",
"SAIL",
"FACT",
"HINDPETRO",
"BHEL",
"HINDZINC",
"TATAELXSI",
"UPL",
"LLOYDSME",
"PIIND",
"LUPIN",
"ZEEL",
"CRISIL",
"MPHASIS",
"IPCALAB",
"FEDERALBNK",
"LICHSGFIN",
"AUROPHARMA",
"KEI",
"THERMAX",
"POONAWALLA",
"IDBI",
"OIL",
"GICRE",
"UNIONBANK",
"MAHABANK",
"BANKINDIA",
"INDIANB",
"PHOENIXLTD",
"EMAMILTD",
"NMDC",
"SJVN",
"NIACL",
"UNOMINDA",
"APLAPOLLO",
"ISEC",
"PAGEIND",
"NHPC",
"CONCOR",
"MAZDOCK",
"OFSS",
"PRESTIGE",
"AJANTPHARM",
"SUZLON",
"GLAND",
"JUBLFOOD",
"BIOCON",
"SUNTV",
"GODREJPROP",
"M_MFIN",
"JKCEMENT",
"BDL",
"METROBRAND",
"PERSISTENT",
"TATATECH",
"SONACOMS",
"TORNTPOWER",
"ALKEM",
"PETRONET",
"AWL",
"IGL",
"BSE",
"HDFCAMC",
"AIAENG",
"MAXHEALTH",
"GMRINFRA",
"IDEA",
"UBL",
"SUMICHEM",
"FORTIS",
"DEVYANI",
"JSL",
"MUTHOOTFIN",
"COFORGE",
"YESBANK",
"SOLARINDS",
"SYNGENE",
"POLYCAB",
"RVNL",
"JSWENERGY",
"ASTRAL",
"KPRMILL",
"ZFCVINDIA",
"STARHEALTH",
"AUBANK",
"LODHA",
"DIXON",
"OBEROIRLTY",
"MANKIND",
"PAYTM",
"INDUSTOWER",
"ENDURANCE",
"ABCAPITAL",
"ABFRL",
"TIINDIA",
"LTF",
"LALPATHLAB",
"POLICYBZR",
"KALYANKJIL",
"JSWINFRA",
"GUJGASLTD",
"LTTS",
"LAURUSLABS",
"IDFCFIRSTB",
"BANDHANBNK",
"DELHIVERY",
"DALBHARAT",
"MANYAVAR",
"KPITTECH",
"FLUOROCHEM",
"NYKAA",
"MSUMI"]