name: Run Python Script on Push

on:
  schedule:
    - cron: '45 3 * * *'
  # push:
  #   branches:
  #     - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install --upgrade --no-cache-dir git+https://github.com/Yash-099/tvdatafeed
          pip install -r requirements.txt
          

      - name: Run script
        run: python3 track_specific_stocks.py
